branches:
  only:
    - master
language: python
compiler:
  - gcc
python:
#  - 2.7
  - 3.6
# setup anaconda
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3.0 ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 3.0 ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ $TRAVIS_PYTHON_VERSION < 3.0 ]]; then export PATH=/home/travis/miniconda2/bin:$PATH; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 3.0 ]]; then export PATH=/home/travis/miniconda3/bin:$PATH; fi
  - conda update --yes conda
  - sudo apt-get -qq update
  - sudo apt-get install -y gsl-bin
  - sudo apt-get install -y libgsl0-dev
  # fix multiprocessing bugs on Travis
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
# install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  - pip install -r requirements.txt
  - git clone https://github.com/LSSTDESC/healsparse.git
  - pushd healsparse
  - python setup.py install
  - popd
  - python setup.py install
script: cd tests && nosetests
cache:
  pip: true
